### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by starsep**
I had issues with mysql-connector (https://stackoverflow.com/questions/43029672/unable-to-find-protobuf-include-directory) so I've set version to exactly 2.1.4

### CODE REVIEW

**Comment by emkael** [comment]
Fair enough, I don't know why I didn't attach requirements.txt by myself. 2.1.4 works for me, so I'm fine with freezing it.

But I see you've added `htmlmin` as a Python module in requiremetns.txt, while build scripts use the executable wrapper.

Maybe it's time to consider using `htmlmin` as a Python module, in that case.
Does the module provide the executable? For example, in my Debian environemnt, these are separate packages, with `htmlmin` even depending on Python3 version of `python-htmlmin` - so they're surely separate.
Does `python -m htmlmin` work as if the `htmlmin` "binary" was called or is some kind of wrapper necessary if I wanted to get rid of calling the standalone `htmlmin` exec?

**Comment by emkael** [comment]
Also, `htmlmin` is not exactly *essential* part of the build process - `make tables editions players` gives fully functional output (only HTML pages are not minimized).

**Comment by starsep** [comment]
> Also, htmlmin is not exactly essential part of the build process - make tables editions players gives fully functional output (only HTML pages are not minimized).

Sure, `htmlmin` is not *essential* but `make` does minimize HTMLs so it seemed like *dependency*.
I guess either `minimize` target shouldn't be dependency of `rankings` or `htmlmin` should be in requirements.txt

> Does the module provide the executable?

It provides python wrapper which is executable.

> Does python -m htmlmin work as if the htmlmin "binary" was called or is some kind of wrapper necessary if I wanted to get rid of calling the standalone htmlmin exec?

I'm not sure :frowning_face:, I guess `python -m htmlmin.command` is equivalent to `htmlmin`.

**Comment by emkael** [comment]
> I guess either minimize target shouldn't be dependency of rankings or htmlmin should be in requirements.txt

Or both. :)

> python -m htmlmin.command is equivalent to htmlmin

Yup, that's the stuff.

Both of the above suggestions (`minimize` is not a target for `all`, but I'm keeping the `htmlmin` module in requirements, and Makefile now uses Python module instead of standalone executable) are now in master.

**Pull request merged**
